"""Statistical distributions for player and team props.

This module is what turns a single posted prop into an entire priced ladder,
and that is the most valuable idea in the props half of this package.

Here is the mechanism. A book posts one anchor number -- strikeouts 6.5 at
-115/-105 -- and that pair of prices tells you what the book thinks the
pitcher's *whole distribution* looks like, not just one threshold. Fit a
distribution to that anchor and you can derive the fair price of 4.5, 5.5,
7.5, 8.5, and every alternate in between.

Then compare those derived prices against the alternates the book actually
posted. They frequently disagree, because alternate lines are generated by a
crude multiplier rather than by the model that produced the main number.
Nobody is attacking the 8.5 alt with real money, so nobody corrects it.

Getting the distribution family right is what makes this work:

* **Counting stats with overdispersion** (strikeouts, receptions, rebounds)
  are negative binomial. Poisson assumes variance equals the mean; real
  strikeout counts have variance around 1.3x their mean because pitchers have
  good and bad days. Using Poisson understates the tails, which is precisely
  where alternate lines live.
* **Rare events** (goals, touchdowns, home runs) are close to Poisson.
* **Continuous, right-skewed totals** (passing and rushing yards) are gamma.
  A normal distribution puts real probability below zero for a running back
  projected at 45 yards, and understates the long tail that anytime-100-yard
  props are priced on.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Protocol

__all__ = [
    "Distribution",
    "PoissonDist",
    "NegativeBinomialDist",
    "NormalDist",
    "GammaDist",
    "build",
    "fit_to_market",
    "ladder",
    "STAT_MODELS",
    "model_for",
]


class Distribution(Protocol):
    """A fitted distribution over a single stat."""

    mean: float

    def sf(self, x: float) -> float:
        """P(X > x). The over probability for a line at x."""
        ...

    def pmf(self, k: int) -> float:
        """P(X == k). Zero for continuous distributions."""
        ...

    def with_mean(self, mean: float) -> "Distribution":
        """Same shape, different center."""
        ...


# ---------------------------------------------------------------------------
# Discrete
# ---------------------------------------------------------------------------


@dataclass
class PoissonDist:
    """Poisson. Correct for genuinely rare, independent events.

    Appropriate for goals, touchdowns, and home runs. Wrong for strikeouts
    and rebounds, where the variance visibly exceeds the mean.
    """

    mean: float

    def pmf(self, k: int) -> float:
        if k < 0:
            return 0.0
        lam = max(self.mean, 1e-9)
        return math.exp(-lam + k * math.log(lam) - math.lgamma(k + 1))

    def cdf(self, k: int) -> float:
        return sum(self.pmf(i) for i in range(0, int(math.floor(k)) + 1))

    def sf(self, x: float) -> float:
        floor = int(math.floor(x))
        if floor < 0:
            return 1.0
        return max(0.0, 1.0 - self.cdf(floor))

    def with_mean(self, mean: float) -> "PoissonDist":
        return PoissonDist(mean=mean)


@dataclass
class NegativeBinomialDist:
    """Negative binomial: a Poisson whose rate itself varies.

    ``dispersion`` is the variance-to-mean ratio. At 1.0 this collapses to
    Poisson; strikeouts sit near 1.35, receptions near 1.25.

    This matters more than it sounds. Overdispersion fattens both tails, so a
    Poisson model systematically underprices "10+ strikeouts" and overprices
    the middle of the ladder. Alternate lines are exactly the tail bets where
    that error is largest.
    """

    mean: float
    dispersion: float = 1.35

    def __post_init__(self) -> None:
        if self.dispersion <= 1.0:
            # Fall back to Poisson behavior rather than producing invalid
            # parameters.
            self.dispersion = 1.0000001

    @property
    def _p(self) -> float:
        return 1.0 / self.dispersion

    @property
    def _r(self) -> float:
        return max(self.mean / (self.dispersion - 1.0), 1e-9)

    def pmf(self, k: int) -> float:
        if k < 0:
            return 0.0
        r, p = self._r, self._p
        return math.exp(
            math.lgamma(k + r)
            - math.lgamma(r)
            - math.lgamma(k + 1)
            + r * math.log(p)
            + k * math.log(1.0 - p)
        )

    def cdf(self, k: int) -> float:
        return sum(self.pmf(i) for i in range(0, int(math.floor(k)) + 1))

    def sf(self, x: float) -> float:
        floor = int(math.floor(x))
        if floor < 0:
            return 1.0
        return max(0.0, 1.0 - self.cdf(floor))

    def with_mean(self, mean: float) -> "NegativeBinomialDist":
        return NegativeBinomialDist(mean=mean, dispersion=self.dispersion)


# ---------------------------------------------------------------------------
# Continuous
# ---------------------------------------------------------------------------


@dataclass
class NormalDist:
    """Normal. Adequate for high-volume symmetric stats like NBA points."""

    mean: float
    sd: float

    def sf(self, x: float) -> float:
        if self.sd <= 0:
            return 1.0 if self.mean > x else 0.0
        return 0.5 * math.erfc((x - self.mean) / (self.sd * math.sqrt(2.0)))

    def pmf(self, k: int) -> float:
        return 0.0

    def with_mean(self, mean: float) -> "NormalDist":
        # Scale the spread with the projection: a 90-yard receiver is more
        # volatile in absolute terms than a 30-yard one.
        ratio = mean / self.mean if self.mean > 0 else 1.0
        return NormalDist(mean=mean, sd=self.sd * math.sqrt(max(ratio, 1e-9)))


@dataclass
class GammaDist:
    """Gamma. The right shape for yardage: non-negative and right-skewed.

    ``cv`` is the coefficient of variation (sd / mean), which is roughly
    stable across players for a given stat -- a receiver projected at 80
    yards and one at 40 have similar *relative* volatility.
    """

    mean: float
    cv: float = 0.62

    @property
    def shape(self) -> float:
        return max(1.0 / (self.cv**2), 1e-6)

    @property
    def scale(self) -> float:
        return max(self.mean / self.shape, 1e-9)

    def sf(self, x: float) -> float:
        if x <= 0:
            return 1.0
        return max(0.0, min(1.0, 1.0 - _lower_gamma_reg(self.shape, x / self.scale)))

    def pmf(self, k: int) -> float:
        return 0.0

    def with_mean(self, mean: float) -> "GammaDist":
        return GammaDist(mean=mean, cv=self.cv)


def _lower_gamma_reg(a: float, x: float) -> float:
    """Regularized lower incomplete gamma P(a, x), for the gamma CDF."""
    if x < 0 or a <= 0:
        return 0.0
    if x == 0:
        return 0.0
    if x < a + 1.0:
        # Series expansion.
        total = 1.0 / a
        term = total
        for n in range(1, 300):
            term *= x / (a + n)
            total += term
            if abs(term) < abs(total) * 1e-14:
                break
        return total * math.exp(-x + a * math.log(x) - math.lgamma(a))
    # Continued fraction for the upper incomplete gamma.
    tiny = 1e-300
    b = x + 1.0 - a
    c = 1.0 / tiny
    d = 1.0 / b
    h = d
    for i in range(1, 300):
        an = -i * (i - a)
        b += 2.0
        d = an * d + b
        if abs(d) < tiny:
            d = tiny
        c = b + an / c
        if abs(c) < tiny:
            c = tiny
        d = 1.0 / d
        delta = d * c
        h *= delta
        if abs(delta - 1.0) < 1e-14:
            break
    upper = math.exp(-x + a * math.log(x) - math.lgamma(a)) * h
    return 1.0 - upper


# ---------------------------------------------------------------------------
# Stat model registry
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class StatModel:
    """Which distribution family a stat follows, and its shape parameter."""

    family: str            # "poisson" | "negbin" | "normal" | "gamma"
    parameter: float       # dispersion, cv, or sd-per-sqrt-mean
    integer: bool          # whole-number outcomes, so whole lines can push
    note: str = ""


# Shape parameters are empirical and reasonably stable across players. The
# projection (the mean) is what varies game to game, and that is exactly the
# quantity fitted from the market's own anchor price.
STAT_MODELS: dict[str, StatModel] = {
    # --- MLB -------------------------------------------------------------
    "strikeouts": StatModel("negbin", 1.35, True, "pitcher Ks are overdispersed"),
    "hits_allowed": StatModel("negbin", 1.25, True),
    "earned_runs": StatModel("negbin", 1.9, True, "very heavy tail on blowup starts"),
    "outs_recorded": StatModel("normal", 0.9, True),
    "walks_allowed": StatModel("negbin", 1.2, True),
    "hits": StatModel("negbin", 1.12, True),
    "total_bases": StatModel("negbin", 1.6, True, "home runs fatten the tail"),
    "rbis": StatModel("negbin", 1.5, True),
    "runs_scored": StatModel("negbin", 1.4, True),
    "home_runs": StatModel("poisson", 1.0, True, "genuinely rare, Poisson holds"),
    "stolen_bases": StatModel("poisson", 1.0, True),
    # --- NFL -------------------------------------------------------------
    "passing_yards": StatModel("gamma", 0.34, False),
    "passing_tds": StatModel("poisson", 1.0, True),
    "completions": StatModel("negbin", 1.15, True),
    "pass_attempts": StatModel("negbin", 1.12, True),
    "interceptions": StatModel("poisson", 1.0, True),
    "rushing_yards": StatModel("gamma", 0.52, False, "one long run dominates"),
    "rush_attempts": StatModel("negbin", 1.2, True),
    "receptions": StatModel("negbin", 1.25, True),
    "receiving_yards": StatModel("gamma", 0.62, False, "highest variance skill stat"),
    "longest_reception": StatModel("gamma", 0.55, False),
    "anytime_td": StatModel("poisson", 1.0, True),
    "tackles_assists": StatModel("negbin", 1.2, True),
    # --- NBA -------------------------------------------------------------
    "points": StatModel("normal", 1.02, True),
    "rebounds": StatModel("negbin", 1.3, True),
    "assists": StatModel("negbin", 1.28, True),
    "threes_made": StatModel("negbin", 1.22, True),
    "steals": StatModel("poisson", 1.0, True),
    "blocks": StatModel("poisson", 1.0, True),
    "turnovers": StatModel("negbin", 1.15, True),
    "pra": StatModel("normal", 1.15, True, "points+rebounds+assists"),
    "pr": StatModel("normal", 1.10, True),
    "pa": StatModel("normal", 1.08, True),
    # --- NHL -------------------------------------------------------------
    "shots_on_goal": StatModel("negbin", 1.25, True),
    "saves": StatModel("negbin", 1.2, True),
    "goals": StatModel("poisson", 1.0, True),
    "player_points": StatModel("poisson", 1.0, True),
}


def model_for(stat: str) -> StatModel:
    """Look up a stat's model, defaulting to a mildly overdispersed count."""
    return STAT_MODELS.get(
        stat.lower().replace(" ", "_"),
        StatModel("negbin", 1.25, True, "unrecognized stat, using a generic count"),
    )


def build(stat: str, mean: float) -> Distribution:
    """Construct a fitted distribution for a stat at a projected mean."""
    model = model_for(stat)
    mean = max(mean, 1e-6)

    if model.family == "poisson":
        return PoissonDist(mean=mean)
    if model.family == "negbin":
        return NegativeBinomialDist(mean=mean, dispersion=model.parameter)
    if model.family == "gamma":
        return GammaDist(mean=mean, cv=model.parameter)
    # Normal: the parameter scales sd with sqrt(mean), which tracks how
    # counting-stat volatility actually grows.
    return NormalDist(mean=mean, sd=max(model.parameter * math.sqrt(mean), 1e-6))


# ---------------------------------------------------------------------------
# Fitting to the market
# ---------------------------------------------------------------------------


def fit_to_market(
    stat: str, line: float, over_probability: float, tol: float = 1e-9
) -> Distribution:
    """Find the projection implied by the market's own price.

    This is the key move. Rather than projecting the player ourselves -- which
    would mean competing with the book's model using worse data -- we take the
    book's anchor price as truth about the *center* of the distribution and
    supply only the *shape*. The shape is stable and empirical; the projection
    is the hard part, and the market has already done it.

    Everything derived from here is therefore a statement about internal
    consistency, not a competing forecast: given that you priced 6.5 at this
    number, your own 8.5 is wrong.
    """
    p = min(max(over_probability, 1e-6), 1.0 - 1e-6)

    lo, hi = 1e-4, max(line * 6.0, 10.0)
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if build(stat, mid).sf(line) < p:
            lo = mid
        else:
            hi = mid
        if hi - lo < tol:
            break
    return build(stat, 0.5 * (lo + hi))


def ladder(dist: Distribution, lines: list[float]) -> dict[float, float]:
    """Fair over-probability at every line in a ladder."""
    return {line: min(max(dist.sf(line), 1e-6), 1.0 - 1e-6) for line in lines}


def standard_ladder(anchor: float, stat: str, spread: int = 4) -> list[float]:
    """Generate the alternate lines a book typically posts around an anchor."""
    model = model_for(stat)
    if model.integer:
        step = 1.0
    else:
        # Yardage props ladder in fives or tens depending on magnitude.
        step = 10.0 if anchor >= 60 else 5.0
    base = anchor
    return [
        round(base + i * step, 1)
        for i in range(-spread, spread + 1)
        if base + i * step > 0
    ]


def push_probability(dist: Distribution, line: float, stat: str) -> float:
    """Probability of landing exactly on a whole-number prop line.

    Matters because books post whole-number prop lines ("over 6 strikeouts")
    where a 6 refunds the bet. A push is not a loss, and pricing it as one
    materially understates the value of the over.
    """
    if not model_for(stat).integer:
        return 0.0
    if abs(line - round(line)) > 1e-9:
        return 0.0
    return dist.pmf(int(round(line)))
